"""PlatformIO pre-build script: compress portal_page.html → portal_html.h

Reads the raw HTML file, gzips it, and writes a C header with the data as a
PROGMEM byte array. The web server serves this with Content-Encoding: gzip
so browsers decompress it automatically.

Usage in platformio.ini:
    extra_scripts = pre:scripts/compress_html.py
"""

import gzip
import os

Import("env")

SRC_DIR = os.path.join(env.subst("$PROJECT_SRC_DIR"))
HTML_IN = os.path.join(SRC_DIR, "portal_page.html")
HDR_OUT = os.path.join(SRC_DIR, "portal_html.h")


def compress_html(source, target, env):
    if not os.path.exists(HTML_IN):
        print(f"[compress_html] WARNING: {HTML_IN} not found, skipping")
        return

    with open(HTML_IN, "r") as f:
        raw = f.read()

    compressed = gzip.compress(raw.encode("utf-8"), compresslevel=9)

    # Check if output already matches (avoid unnecessary rebuilds)
    if os.path.exists(HDR_OUT):
        with open(HDR_OUT, "rb") as f:
            existing = f.read()
        # Quick check: if file contains same size, skip
        if f"const unsigned int PORTAL_HTML_GZ_LEN = {len(compressed)};" in existing.decode("utf-8", errors="ignore"):
            return

    # Format as C byte array
    hex_lines = []
    for i in range(0, len(compressed), 16):
        chunk = compressed[i : i + 16]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))

    header = (
        "// AUTO-GENERATED by scripts/compress_html.py — do not edit\n"
        "#ifndef PORTAL_HTML_H\n"
        "#define PORTAL_HTML_H\n\n"
        "#include <pgmspace.h>\n\n"
        "const uint8_t PORTAL_HTML_GZ[] PROGMEM = {\n"
        + ",\n".join(hex_lines)
        + "\n};\n\n"
        f"const unsigned int PORTAL_HTML_GZ_LEN = {len(compressed)};\n\n"
        "#endif // PORTAL_HTML_H\n"
    )

    with open(HDR_OUT, "w") as f:
        f.write(header)

    print(
        f"[compress_html] {os.path.basename(HTML_IN)}: "
        f"{len(raw)} bytes → {len(compressed)} bytes gzipped "
        f"({100 * len(compressed) / len(raw):.0f}%)"
    )


# Register as a pre-build action
env.AddPreAction("$BUILD_DIR/src/wifi_portal.cpp.o", compress_html)
# Also run if building any src (catches first build)
env.AddPreAction("$BUILD_DIR/src/main.cpp.o", compress_html)
